(
  SELECT (
  SELECT CONCAT(NAME, '(', SUBSTRING(OCCUPATION, 1, 1), ')') as THETEXT
    FROM OCCUPATIONS
)
UNION ALL 
(
  SELECT CONCAT('There are a total of ', COUNT(*),' ', lower(OCCUPATION), (IF (COUNT(*) > 1, 's.',''))) as THETEXT
   FROM OCCUPATIONS GROUP BY OCCUPATION
)
ORDER BY  THETEXT ASC;(NAME, '(', SUBSTRING(OCCUPATION, 1, 1), ')') as THETEXT
    FROM OCCUPATIONS
)
UNION ALL 
(
  SELECT CONCAT('There are a total of ', COUNT(*),' ', lower(OCCUPATION), (IF (COUNT(*) > 1, 's.',''))) as THETEXT
   FROM OCCUPATIONS GROUP BY OCCUPATION
)
ORDER BY  THETEXT ASC;
